local function button_callback(self)
	print("Button was clicked!")
end

function init(self)
end

function final(self)
--	self.druid:final()
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
--	self.druid:on_message(message_id, message, sender)
end


function on_input(self, action_id, action)
--	return self.druid:on_input(action_id, action)
end

function on_reload(self)
end
